#!/usr/bin/env bash

if [[ "$BASH_VERSINFO" -lt "4" ]]; then
	echo "!! Your system Bash is out of date: $BASH_VERSION"
	echo "!! Please upgrade to Bash 4 or greater."
	exit 2
fi

export PLUGIN_PATH=${PLUGIN_PATH:="plugins"}

export BUILDKIT_BUILDERS=${BUILDKIT_BUILDERS:="docker"}
export BUILDKIT_ARTIFACT=${BUILDKIT_ARTIFACT:="image"}
export BUILDKIT_INPUT=${BUILDKIT_INPUT:="stdin"}
export BUILDKIT_OUTPUT=${BUILDKIT_OUTPUT:="docker"}


main() {
	set -eo pipefail; [[ "$TRACE" ]] && set -x

	# Source all plugins
	$(plugn source importer)
	$(plugn source builder)
	$(plugn source exporter)

	# import app
	$BUILDKIT_INPUT:import

	for builder in $BUILDKIT_BUILDERS; do
		$builder:detect-build && $builder:build-$BUILDKIT_ARTIFACT
	done

}

case "$1" in
	plugin) shift; plugn "$@";;
	*) 			main "$@";;
esac
